[package]
name = "events"
version = "0.1.0"
authors = ["Gregor Peach <gregorpeach@gmail.com>"]

[dependencies]
lib_composite = "0.7"

[lib]
crate-type = ["staticlib"]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
