COMPONENT=unit_schedlibtests.o
INTERFACES=
DEPENDENCIES= 
IF_LIB=
ADDITIONAL_LIBS=-lcobj_format $(LIBSLRAW) -lsl_mod_fprr -lsl_thd_static_backend -llkl

include ../../Makefile.subsubdir
MANDITORY_LIB=simple_stklib.o 
